CREATE DATABASE muchos_a_muchos
GO
USE muchos_a_muchos
GO
CREATE TABLE PACIENTES(
DNI INT NOT NULL PRIMARY KEY,
NOMBRES VARCHAR(30) NOT NULL,
APLELLIDOS VARCHAR(30) NOT NULL,
TELEFONO INT NULL
)
GO
CREATE TABLE ESPECIALIDADES(
ID TINYINT NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(30) NOT NULL
)
GO
CREATE TABLE TURNOS(
ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
DNI INT NOT NULL FOREIGN KEY REFERENCES PACIENTES(DNI),
FECHA SMALLDATETIME NOT NULL,
ESPECIALIDAD TINYINT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADES(ID)
)