CREATE DATABASE uno_a_uno
GO
USE uno_a_uno
GO
CREATE TABLE USUARIO(
DNI INT NOT NULL PRIMARY KEY,
NOMBRES VARCHAR(30) NOT NULL,
APELLIDOS VARCHAR(30) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL,
TELEFONO INT NULL
)
GO
CREATE TABLE AFILIACION(
DNI INT NOT NULL,
NRO_AFILIADO INT NOT NULL UNIQUE IDENTITY(100,1),
CONTRASEÑA VARCHAR(8) NOT NULL,
PRIMARY KEY(DNI),
FOREIGN KEY(DNI) REFERENCES USUARIO(DNI)
)
GO
